### PR TITLE
WL-3880: fixing availability data so it works

### PR DESCRIPTION
**Pull request by nicholaswilson100**

### CODE REVIEW

**Comment by nicholaswilson100** [comment]
Linked to https://github.com/ox-it/wl-citations/pull/76 and https://github.com/ox-it/wl-reference/pull/108

**Comment by nicholaswilson100** [comment]
The main changes are 1) adding in the fact that the status of 'Confined' means that the item is available and 2) updating the available and total items on the existing items (that will get displayed)  rather than the items we're iterating through).

**Comment by buckett** [comment]
Sorry for not catching this the first time around.

**Comment by buckett** [comment]
Always nice to have your explanation, putting it in the commit comments makes it much easier to fine next time around.

**Pull request merged**
